model: gpt-5.4-nano-2026-03-17
api: openai
max_tokens: 128000
read_cost: 0.05
write_cost: 0.4
concurrent_requests: 32
temperature: null
top_p: null
use_openai_responses_api: true
reasoning:
  summary: "auto"